INSERT INTO `product`(`product_sid`, `product_name`, `description`, `category_sid`, `unit_price`, `on_sale`, `created_at`) VALUES 
(NULL, 'Scallops over Truffled Mushroom Risotto\r\n', 'with a Brown Butter Herb Sauce\r\n', 4, 88, 1,NOW()),
(NULL, 'Pork Sausage & Bell Pepper Risotto\r\n', 'with Parmesan & Lemon\r\n', 4, 88, 1,NOW()),
(NULL, 'Mushroom & Chive Risotto\r\n', 'swirled with Garlic Herb Butter\r\n', 4, 88, 1,NOW()),
(NULL, 'Balsamic Tomato Parmesan Risotto\r\n', 'with Basil Oil & Zucchini\r\n', 4, 98, 1,NOW()),
(NULL, 'Pork Sausage & Tomato Risotto\r\n', 'with Lemony Zucchini Ribbons\r\n', 4, 108, 1,NOW()),
(NULL, 'Scallops Over Butternut Squash Risotto\r\n', 'with Lemon-Sage Brown Butter\r\n', 4, 108, 1,NOW()),
(NULL, 'Sausage and Pea Risotto\r\n', 'with Lemon and Parmesan\r\n', 4, 98, 1,NOW()),
(NULL, 'Basil-Oil-Topped Parmesan Risotto\r\n', 'with Balsamic Tomatoes and Zucchini\r\n', 4, 98, 1,NOW()),
(NULL, 'Asparagus Risotto\r\n', 'with Garlic Herb Butter and Parmesan\r\n', 4, 98, 1,NOW()),
(NULL, 'Crab Cakes with Tarragon Aioli\r\n', 'over Garlic Herb Risotto with Lemony Zucchini Ribbons\r\n', 4, 108, 1,NOW()),
(NULL, 'Sausage and Tomato Risotto\r\n', 'with Lemony Zucchini Ribbons\r\n', 4, 108, 1,NOW()),
(NULL, '20 oz Rib-Eye Steaks Over Risotto\r\n', 'with Tomato Onion Jam and Freshly Cracked Peppercorns\r\n', 4, 108, 1,NOW()),
(NULL, 'Sausage Pasta Dinner\r\n', 'with a Shallot Zucchini Risotto for Lunch\r\n', 4, 108, 1,NOW()),
(NULL, 'Lemony Shrimp Risotto\r\n', 'with Roasted Zucchini\r\n', 4, 108, 1,NOW()),

